FROM nginx:1.15
RUN apt-get -y update && \
    apt-get -y install net-tools curl vim
COPY /var/jenkins_home/workspace/sg-cms/public/* /usr/share/nginx/html
COPY --from=0 /var/jenkins_home/workspace/sg-cms/manifests/default.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
